// mksyscall_libc.pl -redox -tags redox,amd64 syscall_redox.go
// Code generated by the command above; DO NOT EDIT.

//go:build redox && amd64

package syscall

import "unsafe"

//go:cgo_import_static _cgo_libc_pipe2
//go:cgo_import_static _cgo_libc_getcwd
//go:cgo_import_static _cgo_libc_getgroups
//go:cgo_import_static _cgo_libc_setgroups
//go:cgo_import_static _cgo_libc_fcntl
//go:cgo_import_static _cgo_libc_accept
//go:cgo_import_static _cgo_libc_sendmsg
//go:cgo_import_static _cgo_libc_access
//go:cgo_import_static _cgo_libc_chdir
//go:cgo_import_static _cgo_libc_chmod
//go:cgo_import_static _cgo_libc_chown
//go:cgo_import_static _cgo_libc_chroot
//go:cgo_import_static _cgo_libc_close
//go:cgo_import_static _cgo_libc_dup
//go:cgo_import_static _cgo_libc_fchdir
//go:cgo_import_static _cgo_libc_fchmod
//go:cgo_import_static _cgo_libc_fchown
//go:cgo_import_static _cgo_libc_fpathconf
//go:cgo_import_static _cgo_libc_fstat
//go:cgo_import_static _cgo_libc_getgid
//go:cgo_import_static _cgo_libc_getpid
//go:cgo_import_static _cgo_libc_geteuid
//go:cgo_import_static _cgo_libc_getegid
//go:cgo_import_static _cgo_libc_getppid
//go:cgo_import_static _cgo_libc_getpriority
//go:cgo_import_static _cgo_libc_getrlimit
//go:cgo_import_static _cgo_libc_getrusage
//go:cgo_import_static _cgo_libc_gettimeofday
//go:cgo_import_static _cgo_libc_getuid
//go:cgo_import_static _cgo_libc_kill
//go:cgo_import_static _cgo_libc_lchown
//go:cgo_import_static _cgo_libc_link
//go:cgo_import_static _cgo_libc_listen
//go:cgo_import_static _cgo_libc_lstat
//go:cgo_import_static _cgo_libc_mkdir
//go:cgo_import_static _cgo_libc_mknod
//go:cgo_import_static _cgo_libc_nanosleep
//go:cgo_import_static _cgo_libc_open
//go:cgo_import_static _cgo_libc_pathconf
//go:cgo_import_static _cgo_libc_pread
//go:cgo_import_static _cgo_libc_pwrite
//go:cgo_import_static _cgo_libc_read
//go:cgo_import_static _cgo_libc_readlink
//go:cgo_import_static _cgo_libc_rename
//go:cgo_import_static _cgo_libc_rmdir
//go:cgo_import_static _cgo_libc_lseek
//go:cgo_import_static _cgo_libc_setegid
//go:cgo_import_static _cgo_libc_seteuid
//go:cgo_import_static _cgo_libc_setgid
//go:cgo_import_static _cgo_libc_setpgid
//go:cgo_import_static _cgo_libc_setpriority
//go:cgo_import_static _cgo_libc_setregid
//go:cgo_import_static _cgo_libc_setreuid
//go:cgo_import_static _cgo_libc_setrlimit
//go:cgo_import_static _cgo_libc_setsid
//go:cgo_import_static _cgo_libc_setuid
//go:cgo_import_static _cgo_libc_shutdown
//go:cgo_import_static _cgo_libc_stat
//go:cgo_import_static _cgo_libc_symlink
//go:cgo_import_static _cgo_libc_sync
//go:cgo_import_static _cgo_libc_truncate
//go:cgo_import_static _cgo_libc_posix_getdents
//go:cgo_import_static _cgo_libc_fsync
//go:cgo_import_static _cgo_libc_ftruncate
//go:cgo_import_static _cgo_libc_umask
//go:cgo_import_static _cgo_libc_unlink
//go:cgo_import_static _cgo_libc_utimes
//go:cgo_import_static _cgo_libc_bind
//go:cgo_import_static _cgo_libc_connect
//go:cgo_import_static _cgo_libc_mmap
//go:cgo_import_static _cgo_libc_munmap
//go:cgo_import_static _cgo_libc_sendto
//go:cgo_import_static _cgo_libc_socket
//go:cgo_import_static _cgo_libc_socketpair
//go:cgo_import_static _cgo_libc_uname
//go:cgo_import_static _cgo_libc_write
//go:cgo_import_static _cgo_libc_writev
//go:cgo_import_static _cgo_libc_getsockopt
//go:cgo_import_static _cgo_libc_getpeername
//go:cgo_import_static _cgo_libc_getsockname
//go:cgo_import_static _cgo_libc_setsockopt
//go:cgo_import_static _cgo_libc_recvfrom
//go:cgo_import_static _cgo_libc_recvmsg

//go:linkname libc_pipe2 _cgo_libc_pipe2
//go:linkname libc_Getcwd _cgo_libc_getcwd
//go:linkname libc_getgroups _cgo_libc_getgroups
//go:linkname libc_setgroups _cgo_libc_setgroups
//go:linkname libc_fcntl _cgo_libc_fcntl
//go:linkname libc_accept _cgo_libc_accept
//go:linkname libc_sendmsg _cgo_libc_sendmsg
//go:linkname libc_Access _cgo_libc_access
//go:linkname libc_Chdir _cgo_libc_chdir
//go:linkname libc_Chmod _cgo_libc_chmod
//go:linkname libc_Chown _cgo_libc_chown
//go:linkname libc_Chroot _cgo_libc_chroot
//go:linkname libc_Close _cgo_libc_close
//go:linkname libc_Dup _cgo_libc_dup
//go:linkname libc_Fchdir _cgo_libc_fchdir
//go:linkname libc_Fchmod _cgo_libc_fchmod
//go:linkname libc_Fchown _cgo_libc_fchown
//go:linkname libc_Fpathconf _cgo_libc_fpathconf
//go:linkname libc_Fstat _cgo_libc_fstat
//go:linkname libc_Getgid _cgo_libc_getgid
//go:linkname libc_Getpid _cgo_libc_getpid
//go:linkname libc_Geteuid _cgo_libc_geteuid
//go:linkname libc_Getegid _cgo_libc_getegid
//go:linkname libc_Getppid _cgo_libc_getppid
//go:linkname libc_Getpriority _cgo_libc_getpriority
//go:linkname libc_Getrlimit _cgo_libc_getrlimit
//go:linkname libc_Getrusage _cgo_libc_getrusage
//go:linkname libc_Gettimeofday _cgo_libc_gettimeofday
//go:linkname libc_Getuid _cgo_libc_getuid
//go:linkname libc_Kill _cgo_libc_kill
//go:linkname libc_Lchown _cgo_libc_lchown
//go:linkname libc_Link _cgo_libc_link
//go:linkname libc_listen _cgo_libc_listen
//go:linkname libc_Lstat _cgo_libc_lstat
//go:linkname libc_Mkdir _cgo_libc_mkdir
//go:linkname libc_Mknod _cgo_libc_mknod
//go:linkname libc_Nanosleep _cgo_libc_nanosleep
//go:linkname libc_Open _cgo_libc_open
//go:linkname libc_Pathconf _cgo_libc_pathconf
//go:linkname libc_pread _cgo_libc_pread
//go:linkname libc_pwrite _cgo_libc_pwrite
//go:linkname libc_read _cgo_libc_read
//go:linkname libc_Readlink _cgo_libc_readlink
//go:linkname libc_Rename _cgo_libc_rename
//go:linkname libc_Rmdir _cgo_libc_rmdir
//go:linkname libc_lseek _cgo_libc_lseek
//go:linkname libc_sendfile _cgo_libc_sendfile
//go:linkname libc_Setegid _cgo_libc_setegid
//go:linkname libc_Seteuid _cgo_libc_seteuid
//go:linkname libc_Setgid _cgo_libc_setgid
//go:linkname libc_Setpgid _cgo_libc_setpgid
//go:linkname libc_Setpriority _cgo_libc_setpriority
//go:linkname libc_Setregid _cgo_libc_setregid
//go:linkname libc_Setreuid _cgo_libc_setreuid
//go:linkname libc_setrlimit _cgo_libc_setrlimit
//go:linkname libc_Setsid _cgo_libc_setsid
//go:linkname libc_Setuid _cgo_libc_setuid
//go:linkname libc_shutdown _cgo_libc_shutdown
//go:linkname libc_Stat _cgo_libc_stat
//go:linkname libc_Symlink _cgo_libc_symlink
//go:linkname libc_Sync _cgo_libc_sync
//go:linkname libc_Truncate _cgo_libc_truncate
//go:linkname libc_PosixGetdents _cgo_libc_posix_getdents
//go:linkname libc_Fsync _cgo_libc_fsync
//go:linkname libc_Ftruncate _cgo_libc_ftruncate
//go:linkname libc_Umask _cgo_libc_umask
//go:linkname libc_Unlink _cgo_libc_unlink
//go:linkname libc_utimes _cgo_libc_utimes
//go:linkname libc_bind _cgo_libc_bind
//go:linkname libc_connect _cgo_libc_connect
//go:linkname libc_mmap _cgo_libc_mmap
//go:linkname libc_munmap _cgo_libc_munmap
//go:linkname libc_sendto _cgo_libc_sendto
//go:linkname libc_socket _cgo_libc_socket
//go:linkname libc_socketpair _cgo_libc_socketpair
//go:linkname libc_uname _cgo_libc_uname
//go:linkname libc_write _cgo_libc_write
//go:linkname libc_writev _cgo_libc_writev
//go:linkname libc_getsockopt _cgo_libc_getsockopt
//go:linkname libc_getpeername _cgo_libc_getpeername
//go:linkname libc_getsockname _cgo_libc_getsockname
//go:linkname libc_setsockopt _cgo_libc_setsockopt
//go:linkname libc_recvfrom _cgo_libc_recvfrom
//go:linkname libc_recvmsg _cgo_libc_recvmsg

type libcFunc byte

var (
	libc_pipe2,
	libc_Getcwd,
	libc_getgroups,
	libc_setgroups,
	libc_fcntl,
	libc_accept,
	libc_sendmsg,
	libc_Access,
	libc_Chdir,
	libc_Chmod,
	libc_Chown,
	libc_Chroot,
	libc_Close,
	libc_Dup,
	libc_Fchdir,
	libc_Fchmod,
	libc_Fchown,
	libc_Fpathconf,
	libc_Fstat,
	libc_Getgid,
	libc_Getpid,
	libc_Geteuid,
	libc_Getegid,
	libc_Getppid,
	libc_Getpriority,
	libc_Getrlimit,
	libc_Getrusage,
	libc_Gettimeofday,
	libc_Getuid,
	libc_Kill,
	libc_Lchown,
	libc_Link,
	libc_listen,
	libc_Lstat,
	libc_Mkdir,
	libc_Mknod,
	libc_Nanosleep,
	libc_Open,
	libc_Pathconf,
	libc_pread,
	libc_pwrite,
	libc_read,
	libc_Readlink,
	libc_Rename,
	libc_Rmdir,
	libc_lseek,
	libc_sendfile,
	libc_Setegid,
	libc_Seteuid,
	libc_Setgid,
	libc_Setpgid,
	libc_Setpriority,
	libc_Setregid,
	libc_Setreuid,
	libc_setrlimit,
	libc_Setsid,
	libc_Setuid,
	libc_shutdown,
	libc_Stat,
	libc_Symlink,
	libc_Sync,
	libc_Truncate,
	libc_PosixGetdents,
	libc_Fsync,
	libc_Ftruncate,
	libc_Umask,
	libc_Unlink,
	libc_utimes,
	libc_bind,
	libc_connect,
	libc_mmap,
	libc_munmap,
	libc_sendto,
	libc_socket,
	libc_socketpair,
	libc_uname,
	libc_write,
	libc_writev,
	libc_getsockopt,
	libc_getpeername,
	libc_getsockname,
	libc_setsockopt,
	libc_recvfrom,
	libc_recvmsg libcFunc
)

// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func pipe2(p *[2]_C_int, flags int) (err error) {
	print("bout to sys call libc_pipe2\n")
	_, _, e1 := rawsyscgocall6(unsafe.Pointer(&libc_pipe2), 2, uintptr(unsafe.Pointer(p)), uintptr(flags), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Getcwd(buf []byte) (n int, err error) {
	var _p0 *byte
	if len(buf) > 0 {
		_p0 = &buf[0]
	}
	print("bout to sys call libc_Getcwd\n")
	r0, _, e1 := syscgocall6(unsafe.Pointer(&libc_Getcwd), 2, uintptr(unsafe.Pointer(_p0)), uintptr(len(buf)), 0, 0, 0, 0)
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func getgroups(ngid int, gid *_Gid_t) (n int, err error) {
	print("bout to sys call libc_getgroups\n")
	r0, _, e1 := rawsyscgocall6(unsafe.Pointer(&libc_getgroups), 2, uintptr(ngid), uintptr(unsafe.Pointer(gid)), 0, 0, 0, 0)
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func setgroups(ngid int, gid *_Gid_t) (err error) {
	print("bout to sys call libc_setgroups\n")
	_, _, e1 := rawsyscgocall6(unsafe.Pointer(&libc_setgroups), 2, uintptr(ngid), uintptr(unsafe.Pointer(gid)), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func fcntl(fd int, cmd int, arg int) (val int, err error) {
	print("bout to sys call libc_fcntl\n")
	r0, _, e1 := syscgocall6(unsafe.Pointer(&libc_fcntl), 3, uintptr(fd), uintptr(cmd), uintptr(arg), 0, 0, 0)
	val = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func accept(s int, rsa *RawSockaddrAny, addrlen *_Socklen) (fd int, err error) {
	print("bout to sys call libc_accept\n")
	r0, _, e1 := syscgocall6(unsafe.Pointer(&libc_accept), 3, uintptr(s), uintptr(unsafe.Pointer(rsa)), uintptr(unsafe.Pointer(addrlen)), 0, 0, 0)
	fd = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func sendmsg(s int, msg *Msghdr, flags int) (n int, err error) {
	print("bout to sys call libc_sendmsg\n")
	r0, _, e1 := syscgocall6(unsafe.Pointer(&libc_sendmsg), 3, uintptr(s), uintptr(unsafe.Pointer(msg)), uintptr(flags), 0, 0, 0)
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Access(path string, mode uint32) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	print("bout to sys call libc_Access\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Access), 2, uintptr(unsafe.Pointer(_p0)), uintptr(mode), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Chdir(path string) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	print("bout to sys call libc_Chdir\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Chdir), 1, uintptr(unsafe.Pointer(_p0)), 0, 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Chmod(path string, mode uint32) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	print("bout to sys call libc_Chmod\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Chmod), 2, uintptr(unsafe.Pointer(_p0)), uintptr(mode), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Chown(path string, uid int, gid int) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	print("bout to sys call libc_Chown\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Chown), 3, uintptr(unsafe.Pointer(_p0)), uintptr(uid), uintptr(gid), 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Chroot(path string) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	print("bout to sys call libc_Chroot\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Chroot), 1, uintptr(unsafe.Pointer(_p0)), 0, 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Close(fd int) (err error) {
	print("bout to sys call libc_Close\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Close), 1, uintptr(fd), 0, 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Dup(fd int) (nfd int, err error) {
	print("bout to sys call libc_Dup\n")
	r0, _, e1 := syscgocall6(unsafe.Pointer(&libc_Dup), 1, uintptr(fd), 0, 0, 0, 0, 0)
	nfd = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Fchdir(fd int) (err error) {
	print("bout to sys call libc_Fchdir\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Fchdir), 1, uintptr(fd), 0, 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Fchmod(fd int, mode uint32) (err error) {
	print("bout to sys call libc_Fchmod\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Fchmod), 2, uintptr(fd), uintptr(mode), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Fchown(fd int, uid int, gid int) (err error) {
	print("bout to sys call libc_Fchown\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Fchown), 3, uintptr(fd), uintptr(uid), uintptr(gid), 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Fpathconf(fd int, name int) (val int, err error) {
	print("bout to sys call libc_Fpathconf\n")
	r0, _, e1 := syscgocall6(unsafe.Pointer(&libc_Fpathconf), 2, uintptr(fd), uintptr(name), 0, 0, 0, 0)
	val = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Fstat(fd int, stat *Stat_t) (err error) {
	print("bout to sys call libc_Fstat\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Fstat), 2, uintptr(fd), uintptr(unsafe.Pointer(stat)), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Getgid() (gid int) {
	r0, _, _ := rawsyscgocall6(unsafe.Pointer(&libc_Getgid), 0, 0, 0, 0, 0, 0, 0)
	gid = int(r0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Getpid() (pid int) {
	r0, _, _ := rawsyscgocall6(unsafe.Pointer(&libc_Getpid), 0, 0, 0, 0, 0, 0, 0)
	pid = int(r0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Geteuid() (euid int) {
	r0, _, _ := syscgocall6(unsafe.Pointer(&libc_Geteuid), 0, 0, 0, 0, 0, 0, 0)
	euid = int(r0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Getegid() (egid int) {
	r0, _, _ := syscgocall6(unsafe.Pointer(&libc_Getegid), 0, 0, 0, 0, 0, 0, 0)
	egid = int(r0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Getppid() (ppid int) {
	r0, _, _ := syscgocall6(unsafe.Pointer(&libc_Getppid), 0, 0, 0, 0, 0, 0, 0)
	ppid = int(r0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Getpriority(which int, who int) (n int, err error) {
	print("bout to sys call libc_Getpriority\n")
	r0, _, e1 := syscgocall6(unsafe.Pointer(&libc_Getpriority), 2, uintptr(which), uintptr(who), 0, 0, 0, 0)
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Getrlimit(which int, lim *Rlimit) (err error) {
	print("bout to sys call libc_Getrlimit\n")
	_, _, e1 := rawsyscgocall6(unsafe.Pointer(&libc_Getrlimit), 2, uintptr(which), uintptr(unsafe.Pointer(lim)), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Getrusage(who int, rusage *Rusage) (err error) {
	print("bout to sys call libc_Getrusage\n")
	_, _, e1 := rawsyscgocall6(unsafe.Pointer(&libc_Getrusage), 2, uintptr(who), uintptr(unsafe.Pointer(rusage)), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Gettimeofday(tv *Timeval) (err error) {
	print("bout to sys call libc_Gettimeofday\n")
	_, _, e1 := rawsyscgocall6(unsafe.Pointer(&libc_Gettimeofday), 1, uintptr(unsafe.Pointer(tv)), 0, 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Getuid() (uid int) {
	r0, _, _ := rawsyscgocall6(unsafe.Pointer(&libc_Getuid), 0, 0, 0, 0, 0, 0, 0)
	uid = int(r0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Kill(pid int, signum Signal) (err error) {
	print("bout to sys call libc_Kill\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Kill), 2, uintptr(pid), uintptr(signum), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Lchown(path string, uid int, gid int) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	print("bout to sys call libc_Lchown\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Lchown), 3, uintptr(unsafe.Pointer(_p0)), uintptr(uid), uintptr(gid), 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Link(path string, link string) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	var _p1 *byte
	_p1, err = BytePtrFromString(link)
	if err != nil {
		return
	}
	print("bout to sys call libc_Link\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Link), 2, uintptr(unsafe.Pointer(_p0)), uintptr(unsafe.Pointer(_p1)), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Listen(s int, backlog int) (err error) {
	print("bout to sys call libc_listen\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_listen), 2, uintptr(s), uintptr(backlog), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Lstat(path string, stat *Stat_t) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	print("bout to sys call libc_Lstat\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Lstat), 2, uintptr(unsafe.Pointer(_p0)), uintptr(unsafe.Pointer(stat)), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Mkdir(path string, mode uint32) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	print("bout to sys call libc_Mkdir\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Mkdir), 2, uintptr(unsafe.Pointer(_p0)), uintptr(mode), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Mknod(path string, mode uint32, dev int) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	print("bout to sys call libc_Mknod\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Mknod), 3, uintptr(unsafe.Pointer(_p0)), uintptr(mode), uintptr(dev), 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Nanosleep(time *Timespec, leftover *Timespec) (err error) {
	print("bout to sys call libc_Nanosleep\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Nanosleep), 2, uintptr(unsafe.Pointer(time)), uintptr(unsafe.Pointer(leftover)), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Open(path string, mode int, perm uint32) (fd int, err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	print("bout to sys call libc_Open\n")
	r0, _, e1 := syscgocall6(unsafe.Pointer(&libc_Open), 3, uintptr(unsafe.Pointer(_p0)), uintptr(mode), uintptr(perm), 0, 0, 0)
	fd = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Pathconf(path string, name int) (val int, err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	print("bout to sys call libc_Pathconf\n")
	r0, _, e1 := syscgocall6(unsafe.Pointer(&libc_Pathconf), 2, uintptr(unsafe.Pointer(_p0)), uintptr(name), 0, 0, 0, 0)
	val = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func pread(fd int, p []byte, offset int64) (n int, err error) {
	var _p0 *byte
	if len(p) > 0 {
		_p0 = &p[0]
	}
	print("bout to sys call libc_pread\n")
	r0, _, e1 := syscgocall6(unsafe.Pointer(&libc_pread), 4, uintptr(fd), uintptr(unsafe.Pointer(_p0)), uintptr(len(p)), uintptr(offset), 0, 0)
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func pwrite(fd int, p []byte, offset int64) (n int, err error) {
	var _p0 *byte
	if len(p) > 0 {
		_p0 = &p[0]
	}
	print("bout to sys call libc_pwrite\n")
	r0, _, e1 := syscgocall6(unsafe.Pointer(&libc_pwrite), 4, uintptr(fd), uintptr(unsafe.Pointer(_p0)), uintptr(len(p)), uintptr(offset), 0, 0)
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func read(fd int, p []byte) (n int, err error) {
	var _p0 *byte
	if len(p) > 0 {
		_p0 = &p[0]
	}
	print("bout to sys call libc_read\n")
	r0, _, e1 := syscgocall6(unsafe.Pointer(&libc_read), 3, uintptr(fd), uintptr(unsafe.Pointer(_p0)), uintptr(len(p)), 0, 0, 0)
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Readlink(path string, buf []byte) (n int, err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	var _p1 *byte
	if len(buf) > 0 {
		_p1 = &buf[0]
	}
	print("bout to sys call libc_Readlink\n")
	r0, _, e1 := syscgocall6(unsafe.Pointer(&libc_Readlink), 3, uintptr(unsafe.Pointer(_p0)), uintptr(unsafe.Pointer(_p1)), uintptr(len(buf)), 0, 0, 0)
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Rename(from string, to string) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(from)
	if err != nil {
		return
	}
	var _p1 *byte
	_p1, err = BytePtrFromString(to)
	if err != nil {
		return
	}
	print("bout to sys call libc_Rename\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Rename), 2, uintptr(unsafe.Pointer(_p0)), uintptr(unsafe.Pointer(_p1)), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Rmdir(path string) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	print("bout to sys call libc_Rmdir\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Rmdir), 1, uintptr(unsafe.Pointer(_p0)), 0, 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Seek(fd int, offset int64, whence int) (newoffset int64, err error) {
	print("bout to sys call libc_lseek\n")
	r0, _, e1 := syscgocall6(unsafe.Pointer(&libc_lseek), 3, uintptr(fd), uintptr(offset), uintptr(whence), 0, 0, 0)
	newoffset = int64(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func sendfile(outfd int, infd int, offset *int64, count int) (written int, err error) {
	print("bout to sys call libc_sendfile\n")
	r0, _, e1 := syscgocall6(unsafe.Pointer(&libc_sendfile), 4, uintptr(outfd), uintptr(infd), uintptr(unsafe.Pointer(offset)), uintptr(count), 0, 0)
	written = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Setegid(egid int) (err error) {
	print("bout to sys call libc_Setegid\n")
	_, _, e1 := rawsyscgocall6(unsafe.Pointer(&libc_Setegid), 1, uintptr(egid), 0, 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Seteuid(euid int) (err error) {
	print("bout to sys call libc_Seteuid\n")
	_, _, e1 := rawsyscgocall6(unsafe.Pointer(&libc_Seteuid), 1, uintptr(euid), 0, 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Setgid(gid int) (err error) {
	print("bout to sys call libc_Setgid\n")
	_, _, e1 := rawsyscgocall6(unsafe.Pointer(&libc_Setgid), 1, uintptr(gid), 0, 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Setpgid(pid int, pgid int) (err error) {
	print("bout to sys call libc_Setpgid\n")
	_, _, e1 := rawsyscgocall6(unsafe.Pointer(&libc_Setpgid), 2, uintptr(pid), uintptr(pgid), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Setpriority(which int, who int, prio int) (err error) {
	print("bout to sys call libc_Setpriority\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Setpriority), 3, uintptr(which), uintptr(who), uintptr(prio), 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Setregid(rgid int, egid int) (err error) {
	print("bout to sys call libc_Setregid\n")
	_, _, e1 := rawsyscgocall6(unsafe.Pointer(&libc_Setregid), 2, uintptr(rgid), uintptr(egid), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Setreuid(ruid int, euid int) (err error) {
	print("bout to sys call libc_Setreuid\n")
	_, _, e1 := rawsyscgocall6(unsafe.Pointer(&libc_Setreuid), 2, uintptr(ruid), uintptr(euid), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func setrlimit(which int, lim *Rlimit) (err error) {
	print("bout to sys call libc_setrlimit\n")
	_, _, e1 := rawsyscgocall6(unsafe.Pointer(&libc_setrlimit), 2, uintptr(which), uintptr(unsafe.Pointer(lim)), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Setsid() (pid int, err error) {
	print("bout to sys call libc_Setsid\n")
	r0, _, e1 := rawsyscgocall6(unsafe.Pointer(&libc_Setsid), 0, 0, 0, 0, 0, 0, 0)
	pid = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Setuid(uid int) (err error) {
	print("bout to sys call libc_Setuid\n")
	_, _, e1 := rawsyscgocall6(unsafe.Pointer(&libc_Setuid), 1, uintptr(uid), 0, 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Shutdown(s int, how int) (err error) {
	print("bout to sys call libc_shutdown\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_shutdown), 2, uintptr(s), uintptr(how), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Stat(path string, stat *Stat_t) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	print("bout to sys call libc_Stat\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Stat), 2, uintptr(unsafe.Pointer(_p0)), uintptr(unsafe.Pointer(stat)), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}

// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Symlink(path string, link string) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	var _p1 *byte
	_p1, err = BytePtrFromString(link)
	if err != nil {
		return
	}
	print("bout to sys call libc_Symlink\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Symlink), 2, uintptr(unsafe.Pointer(_p0)), uintptr(unsafe.Pointer(_p1)), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Sync() (err error) {
	print("bout to sys call libc_Sync\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Sync), 0, 0, 0, 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Truncate(path string, length int64) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	print("bout to sys call libc_Truncate\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Truncate), 2, uintptr(unsafe.Pointer(_p0)), uintptr(length), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func PosixGetdents(fd int, buf []byte, flags int) (n int, err error) {
	var _p0 *byte
	if len(buf) > 0 {
		_p0 = &buf[0]
	}
	print("bout to sys call libc_PosixGetdents\n")
	r0, _, e1 := syscgocall6(unsafe.Pointer(&libc_PosixGetdents), 4, uintptr(unsafe.Pointer(_p0)), uintptr(len(buf)), uintptr(flags), 0, 0, 0)
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Fsync(fd int) (err error) {
	print("bout to sys call libc_Fsync\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Fsync), 1, uintptr(fd), 0, 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Ftruncate(fd int, length int64) (err error) {
	print("bout to sys call libc_Ftruncate\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Ftruncate), 2, uintptr(fd), uintptr(length), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Umask(newmask int) (oldmask int) {
	r0, _, _ := syscgocall6(unsafe.Pointer(&libc_Umask), 1, uintptr(newmask), 0, 0, 0, 0, 0)
	oldmask = int(r0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Unlink(path string) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	print("bout to sys call libc_Unlink\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_Unlink), 1, uintptr(unsafe.Pointer(_p0)), 0, 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func utimes(path string, times *[2]Timeval) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	print("bout to sys call libc_utimes\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_utimes), 2, uintptr(unsafe.Pointer(_p0)), uintptr(unsafe.Pointer(times)), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func bind(s int, addr unsafe.Pointer, addrlen _Socklen) (err error) {
	print("bout to sys call libc_bind\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_bind), 3, uintptr(s), uintptr(addr), uintptr(addrlen), 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func connect(s int, addr unsafe.Pointer, addrlen _Socklen) (err error) {
	print("bout to sys call libc_connect\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_connect), 3, uintptr(s), uintptr(addr), uintptr(addrlen), 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func mmap(addr uintptr, length uintptr, prot int, flag int, fd int, pos int64) (ret uintptr, err error) {
	print("bout to sys call libc_mmap\n")
	r0, _, e1 := syscgocall6(unsafe.Pointer(&libc_mmap), 6, uintptr(addr), uintptr(length), uintptr(prot), uintptr(flag), uintptr(fd), uintptr(pos))
	ret = uintptr(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func munmap(addr uintptr, length uintptr) (err error) {
	print("bout to sys call libc_munmap\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_munmap), 2, uintptr(addr), uintptr(length), 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func sendto(s int, buf []byte, flags int, to unsafe.Pointer, addrlen _Socklen) (err error) {
	var _p0 *byte
	if len(buf) > 0 {
		_p0 = &buf[0]
	}
	print("bout to sys call libc_sendto\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_sendto), 6, uintptr(s), uintptr(unsafe.Pointer(_p0)), uintptr(len(buf)), uintptr(flags), uintptr(to), uintptr(addrlen))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func socket(domain int, typ int, proto int) (fd int, err error) {
	print("bout to sys call libc_socket\n")
	r0, _, e1 := syscgocall6(unsafe.Pointer(&libc_socket), 3, uintptr(domain), uintptr(typ), uintptr(proto), 0, 0, 0)
	fd = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func socketpair(domain int, typ int, proto int, fd *[2]int32) (err error) {
	print("bout to sys call libc_socketpair\n")
	_, _, e1 := rawsyscgocall6(unsafe.Pointer(&libc_socketpair), 4, uintptr(domain), uintptr(typ), uintptr(proto), uintptr(unsafe.Pointer(fd)), 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Uname(buf *Utsname) (err error) {
	print("bout to sys call libc_uname\n")
	_, _, e1 := rawsyscgocall6(unsafe.Pointer(&libc_uname), 1, uintptr(unsafe.Pointer(buf)), 0, 0, 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func write(fd int, p []byte) (n int, err error) {
	var _p0 *byte
	if len(p) > 0 {
		_p0 = &p[0]
	}
	r0, _, e1 := syscgocall6(unsafe.Pointer(&libc_write), 3, uintptr(fd), uintptr(unsafe.Pointer(_p0)), uintptr(len(p)), 0, 0, 0)
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func writev(fd int, iovecs []Iovec) (n uintptr, err error) {
	var _p0 *Iovec
	if len(iovecs) > 0 {
		_p0 = &iovecs[0]
	}
	print("bout to sys call libc_writev\n")
	r0, _, e1 := syscgocall6(unsafe.Pointer(&libc_writev), 3, uintptr(fd), uintptr(unsafe.Pointer(_p0)), uintptr(len(iovecs)), 0, 0, 0)
	n = uintptr(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func getsockopt(s int, level int, name int, val unsafe.Pointer, vallen *_Socklen) (err error) {
	print("bout to sys call libc_getsockopt\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_getsockopt), 5, uintptr(s), uintptr(level), uintptr(name), uintptr(val), uintptr(unsafe.Pointer(vallen)), 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func getpeername(fd int, rsa *RawSockaddrAny, addrlen *_Socklen) (err error) {
	print("bout to sys call libc_getpeername\n")
	_, _, e1 := rawsyscgocall6(unsafe.Pointer(&libc_getpeername), 3, uintptr(fd), uintptr(unsafe.Pointer(rsa)), uintptr(unsafe.Pointer(addrlen)), 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func getsockname(fd int, rsa *RawSockaddrAny, addrlen *_Socklen) (err error) {
	print("bout to sys call libc_getsockname\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_getsockname), 3, uintptr(fd), uintptr(unsafe.Pointer(rsa)), uintptr(unsafe.Pointer(addrlen)), 0, 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func setsockopt(s int, level int, name int, val unsafe.Pointer, vallen uintptr) (err error) {
	print("bout to sys call libc_setsockopt\n")
	_, _, e1 := syscgocall6(unsafe.Pointer(&libc_setsockopt), 5, uintptr(s), uintptr(level), uintptr(name), uintptr(val), uintptr(vallen), 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func recvfrom(fd int, p []byte, flags int, from *RawSockaddrAny, fromlen *_Socklen) (n int, err error) {
	var _p0 *byte
	if len(p) > 0 {
		_p0 = &p[0]
	}
	print("bout to sys call libc_recvfrom\n")
	r0, _, e1 := syscgocall6(unsafe.Pointer(&libc_recvfrom), 6, uintptr(fd), uintptr(unsafe.Pointer(_p0)), uintptr(len(p)), uintptr(flags), uintptr(unsafe.Pointer(from)), uintptr(unsafe.Pointer(fromlen)))
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func recvmsg(s int, msg *Msghdr, flags int) (n int, err error) {
	print("bout to sys call libc_recvmsg\n")
	r0, _, e1 := syscgocall6(unsafe.Pointer(&libc_recvmsg), 3, uintptr(s), uintptr(unsafe.Pointer(msg)), uintptr(flags), 0, 0, 0)
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
